# Generated by Django 6.0.2 on 2026-02-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacTable',
            fields=[
                ('PacID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
            ],
        ),
    ]
