# Generated by Django 6.0.2 on 2026-02-15 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Course', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('PacID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacsystem.pactable')),
            ],
        ),
    ]
