# Generated by Django 6.0.2 on 2026-02-17 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacsystem', '0002_studenttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='PacID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacsystem.pactable'),
        ),
    ]
