# Generated by Django 6.0.2 on 2026-02-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacsystem', '0003_alter_studenttable_pacid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pactable',
            name='Department',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pactable',
            name='FirstName',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pactable',
            name='LastName',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='Course',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='FirstName',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='LastName',
            field=models.CharField(max_length=64),
        ),
    ]
