# Generated by Django 6.0.2 on 2026-02-24 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacsystem', '0004_alter_pactable_department_alter_pactable_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='PacID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacsystem.pactable'),
        ),
    ]
